const entrenamientos = [
	{
		id: 1,
		tipo: "resistencia",
		nombre: "Kangoo Jumps",
		enlace: "kangoo-jumps.html",
		image: "kangoo-jumps.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 45 minutos de actividad.",
				precio: 1500,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1800,
				id: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 45 minutos de actividad.",
				precio: 2300,
				idplan:3,
			},
		],
		destacado: 1,
	},
	{
		id: 2,
		tipo: "resistencia",
		nombre: "Trampolines",
		enlace: "trampolines.html",
		image: "trampolines.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 45 minutos de actividad.",
				precio: 1500,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1800,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 45 minutos de actividad.",
				precio: 2300,
				idplan: 3,
			},
		],
		destacado: 0,
	},
	{
		id: 3,
		tipo: "resistencia",
		nombre: "X55",
		enlace: "x55.html",
		image: "x55.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 45 minutos de actividad.",
				precio: 1500,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1800,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 45 minutos de actividad.",
				precio: 2300,
				idplan: 3,
			},
		],
		destacado: 0,
	},
	{
		id: 4,
		tipo: "resistencia",
		nombre: "Funcional",
		enlace: "funcional.html",
		image: "funcional.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 45 minutos de actividad.",
				precio: 1500,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1800,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 45 minutos de actividad.",
				precio: 2300,
				idplan: 3,
			},
		],
		destacado: 0,
	},
	{
		id: 5,
		tipo: "fuerza",
		nombre: "Cross Fit",
		enlace: "cross-fit.html",
		image: "cross-fit.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 45 minutos de actividad.",
				precio: 1500,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1800,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 45 minutos de actividad.",
				precio: 2300,
				idplan: 3,
			},
		],
		destacado: 1,
	},
	{
		id: 6,
		tipo: "fuerza",
		nombre: "Musculación",
		enlace: "musculacion.html",
		image: "musculacion.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1200,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Tres veces a la semana, 1 hora de actividad.",
				precio: 1500,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Cuatro veces a la semana, 1 hora de actividad.",
				precio: 2000,
				idplan: 3,
			},
		],
		destacado: 0,
	},
	{
		id: 7,
		tipo: "pesoCorporal",
		nombre: "Fight Do",
		enlace: "fight-do.html",
		image: "fight-do.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1500,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Tres veces a la semana, 1 hora de actividad.",
				precio: 1800,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Cuatro veces a la semana, 1 hora de actividad.",
				precio: 2200,
				idplan: 3,
			},
		],
		destacado: 1,
	},
	{
		id: 8,
		tipo: "pesoCorporal",
		nombre: "Zumba",
		enlace: "zumba.html",
		image: "zumba.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Dos veces a la semana, 45 minutos de actividad.",
				precio: 1200,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Tres veces a la semana, 1 hora de actividad.",
				precio: 1500,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Cuatro veces a la semana, 1 hora de actividad.",
				precio: 2000,
				idplan: 3,
			},
		],
		destacado: 0,
	},
	{
		id: 9,
		tipo: "calma",
		nombre: "Yoga",
		enlace: "yoga.html",
		image: "yoga.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 1 hora de actividad.",
				precio: 1000,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 1 hora de actividad.",
				precio: 1300,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 1:30 hora de actividad.",
				precio: 1800,
				idplan: 3,
			},
		],
		destacado: 0,
	},
	{
		id: 10,
		tipo: "calma",
		nombre: "Streching",
		enlace: "streching.html",
		image: "streching.png",
		planes: [
			{
				nombreplan: "Principiante",
				detalle: "Una vez a la semana, 45 minutos de actividad.",
				precio: 1000,
				idplan: 1,
			},
			{
				nombreplan: "Intermedio",
				detalle: "Dos veces a la semana, 45 minuto de actividad.",
				precio: 1300,
				idplan: 2,
			},
			{
				nombreplan: "Avanzando",
				detalle: "Tres veces a la semana, 1 hora de actividad.",
				precio: 1800,
				idplan: 3,
			},
		],
		destacado: 0,
	},
];


